### ISSUE TITLE
KeyError at Draft a coexpression-based network

### ISSUE THREAD

**Issue by yolcasmar** [gao-lab/GLUE#117]
Hi,

Thank you for providing this amazing tool!

I've encountered some issues while trying to build a co-expression-based draft network in the 'Regulatory inference' tutorial.
When I execute the following command:

`!pyscenic grn rna.loom tfs.txt \
    -o draft_grn.csv --seed 0 --num_workers 20 \
    --cell_id_attribute cells --gene_attribute genes`

I encounter the following error:
`Traceback (most recent call last):
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/loompy/attribute_manager.py", line 115, in __getattr__
    vals = self.__dict__["storage"][name]
KeyError: 'genes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yolanda/miniforge3/envs/scglue/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 59, in find_adjacencies_command
    ex_mtx = load_exp_matrix(
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/pyscenic/cli/utils.py", line 134, in load_exp_matrix
    return load_exp_matrix_as_loom(
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/pyscenic/cli/utils.py", line 88, in load_exp_matrix_as_loom
...
    return self.__getattr__(thing)
  File "/home/yolanda/miniforge3/envs/scglue/lib/python3.10/site-packages/loompy/attribute_manager.py", line 123, in __getattr__
    raise AttributeError(f"'{type(self)}' object has no attribute '{name}'")
AttributeError: '<class 'loompy.attribute_manager.AttributeManager'>' object has no attribute 'genes'`

I have successfully completed previous tutorials without any issues, so I'm curious as to what might be causing this problem.

Thank you,
Yolanda

**Comment by Jeff1995** [comment]
Hi @yolcasmar, thanks for your interest in GLUE! Could you try assigning the `name` to `rna.obs_names` and `rna.var_names` before saving it to loom? This can be done by the following commands:

```py
rna.obs_names.name = "cells"
rna.var_names.name = "genes"
```
