### ISSUE TITLE
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval

### ISSUE THREAD

**Issue by Jeffyang123** [gao-lab/GLUE#53]
!pyGenomeTracks --tracks tracks.ini --region chr2:22550534-22765544 --outFileName "tracks.png" 
 
this error about this file:gene2peak.links

INFO:pygenometracks.tracksClass:initialize 1. [Score]
 21%|███████▊                             | 468/2225 [00:00<00:00, 11699.87it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/R6/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracksClass.py", line 108, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/GenomeTrack.py", line 63, in __init__
    self.set_properties_defaults()
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/LinksTrack.py", line 132, in set_properties_defaults
    self.interval_tree, min_score, max_score, has_score = self.process_link_file(self.properties['region'])
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/LinksTrack.py", line 502, in process_link_file
    interval_tree[chrom1].add(Interval(mid1, mid2, [start1, end1, start2, end2, score]))
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/intervaltree/intervaltree.py", line 324, in add
    raise ValueError(
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(114201510.0, 114201468.5, [114201109, 114201911, 114201468, 114201469, 0.9999999403953552])

**Comment by Jeffyang123** [comment]
gene2peak.links 转为bedpe 格式查看 出来的结果 有点奇怪 很多地方的一个位点有几十条链接向外发射。

**Comment by Jeff1995** [comment]
Sorry for the last response. Please check #52.
