### ISSUE TITLE
gene2peak.links  rise error

### ISSUE THREAD

**Issue by Jeffyang123** [gao-lab/GLUE#54]
生成的这个文件画图会报错 why?
!pyGenomeTracks --tracks tracks.ini --region chr2:22550534-22765544 --outFileName "tracks.png" 

INFO:pygenometracks.tracksClass:initialize 1. [Score]
  0%|                                        | 1/2228 [00:00<00:00, 6594.82it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/R6/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracksClass.py", line 108, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/GenomeTrack.py", line 63, in __init__
    self.set_properties_defaults()
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/LinksTrack.py", line 132, in set_properties_defaults
    self.interval_tree, min_score, max_score, has_score = self.process_link_file(self.properties['region'])
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/pygenometracks/tracks/LinksTrack.py", line 502, in process_link_file
    interval_tree[chrom1].add(Interval(mid1, mid2, [start1, end1, start2, end2, score]))
  File "/opt/conda/envs/R6/lib/python3.10/site-packages/intervaltree/intervaltree.py", line 324, in add
    raise ValueError(
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(21367693.5, 21367541.5, [21367152, 21368235, 21367541, 21367542, 0.9733458757400513])

**Comment by Jeff1995** [comment]
Sorry for the late response. Please check #52.
